@startuml AddCoupon
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CouponView [
  <<view>>
  :CouponPage
]

participant AddCouponModalView [
  <<view>>
  :AddCouponModal
]

participant CouponController [
  <<controller>>
  :CouponController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Coupon Page
activate CouponView
DashboardView -> CouponView: Redirect to Coupon Page
deactivate DashboardView

CouponView -->> Admin: Show Coupon Page

Admin -> CouponView: Click Add Button

activate AddCouponModalView
CouponView -> AddCouponModalView: Open Coupon Form Modal
AddCouponModalView -->> Admin: Show Coupon Form Modal

Admin -> AddCouponModalView: Fill Coupon Form
Admin -> AddCouponModalView: Click Save Button

activate CouponController
AddCouponModalView -> CouponController: addCoupon()
deactivate AddCouponModalView
alt invalid
    CouponController -->> CouponView: Return Error Message
    CouponView -->> Admin: showErrorPopup()
else valid
    CouponController -->> CouponView: Return Success Message
    CouponView -->> Admin: showSuccessPopup()
end

deactivate CouponController

deactivate Admin
deactivate CouponView
@enduml
