@startuml AddProgram
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Programs Page;
|System|
:Show Programs Page;
|Admin|
:Click Add Button;
|System|
:Redirect to Add Program Page;
|Admin|
repeat :Fill Program Form;
    :Click Save Button on Form;
    |System|
    :Validate Data;
    backward: Show Error Message;
repeat while (valid?) is (no)
-> yes;
|System|
:Show Success Popup;
:Redirect to Program Details Page;
stop
@enduml
