@startuml AddProgram
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ProgramsView [
  <<view>>
  :ProgramsPage
]

participant AddProgramPageView [
  <<view>>
  :AddProgramPage
]

participant ProgramController [
  <<controller>>
  :ProgramController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Programs Page
activate ProgramsView
DashboardView -> ProgramsView: Redirect to Programs Page
deactivate DashboardView
ProgramsView -->> Admin: Show Programs Page

Admin -> ProgramsView: Click Add Button

activate AddProgramPageView
ProgramsView -> AddProgramPageView: Redirect to Add Program Page
AddProgramPageView -->> Admin: Show Add Program Page

Admin -> AddProgramPageView: Fill Program Form
Admin -> AddProgramPageView: Click Save Button

activate ProgramController
AddProgramPageView -> ProgramController: addProgram()
alt invalid
    ProgramController -->> AddProgramPageView: Return Error Message
    AddProgramPageView -->> Admin: showErrorPopup()
else valid
    ProgramController -->> AddProgramPageView: Return Validation Result
    deactivate ProgramController
    AddProgramPageView -->> Admin: showSuccessPopup()
    AddProgramPageView -->> Admin: Redirect to Program Details Page
end

deactivate Admin
deactivate ProgramsView
deactivate AddProgramPageView
@enduml
