@startuml ManageCourseEnrollments
actor Student
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant EnrollmentsPageView [
  <<view>>
  :EnrollmentsPage
]

activate Student
activate LoginPageView
Student -> LoginPageView: Login as Student
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard
deactivate LoginPageView

DashboardView -->> Student: Show Dashboard

Student -> DashboardView: Visit Enrollments Page
activate EnrollmentsPageView
DashboardView -> EnrollmentsPageView: Redirect to Enrollments Page
deactivate DashboardView

EnrollmentsPageView -->> Student: Show Enrollments Page

deactivate Student
deactivate EnrollmentsPageView
@enduml
