@startuml ChangeDayStatus
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Day Page;
|System|
:Show Day Page;
|Admin|
:Click Change Status Button on a Day;
|System|
:Change Status of Day;
:Show Success Popup;
stop
@enduml
