@startuml EditFAQ
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant FAQView [
  <<view>>
  :FAQPage
]

participant EditFAQModalView [
  <<view>>
  :EditFAQModal
]

participant FAQController [
  <<controller>>
  :FAQController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit FAQ Page
activate FAQView
DashboardView -> FAQView: Redirect to FAQ Page
deactivate DashboardView

FAQView -->> Admin: Show FAQ Page

Admin -> FAQView: Click Edit Button on FAQ

activate EditFAQModalView
FAQView -> EditFAQModalView: Open Edit FAQ Form Modal
EditFAQModalView -->> Admin: Show Edit FAQ Form Modal

Admin -> EditFAQModalView: Edit Data in Form
Admin -> EditFAQModalView: Click Save Button on Modal

activate FAQController
EditFAQModalView -> FAQController: editFAQ()
deactivate EditFAQModalView
alt invalid
    FAQController -->> FAQView: Return Error Message
    FAQView -->> Admin: showErrorPopup()
else valid
    FAQController -->> FAQView: Return Success Message
    FAQView -->> Admin: showSuccessPopup()
end

deactivate FAQController

deactivate Admin
deactivate FAQView
@enduml
