@startuml AddPeriod
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant PeriodView [
  <<view>>
  :PeriodPage
]

participant AddPeriodModalView [
  <<view>>
  :AddPeriodModal
]

participant PeriodController [
  <<controller>>
  :PeriodController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Period Page
activate PeriodView
DashboardView -> PeriodView: Redirect to Period Page
deactivate DashboardView

PeriodView -->> Admin: Show Period Page

Admin -> PeriodView: Click Add Button

activate AddPeriodModalView
PeriodView -> AddPeriodModalView: Open Period Form Modal
AddPeriodModalView -->> Admin: Show Period Form Modal

Admin -> AddPeriodModalView: Fill Period Form
Admin -> AddPeriodModalView: Click Save Button

activate PeriodController
AddPeriodModalView -> PeriodController: addPeriod()
deactivate AddPeriodModalView
alt invalid
    PeriodController -->> PeriodView: Return Error Message
    PeriodView -->> Admin: showErrorPopup()
else valid
    PeriodController -->> PeriodView: Return Success Message
    PeriodView -->> Admin: showSuccessPopup()
end

deactivate PeriodController

deactivate Admin
deactivate PeriodView
@enduml
