@startuml AddCourse
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Program Details Page;
|System|
:Show Program Details Page;
|Admin|
:Click "Add a New Course" Button;
|System|
:Show Form for New Course;
|Admin|
repeat :Fill Course Form;
:Click Save Button on Form;
|System|
:Validate Data;
backward: Show Error Message;
repeat while (valid?) is (no)
-> yes;
|Admin|
:Redirect to Course Details Page;
|System|
:Show Success Popup (Course Added);
stop
@enduml
