@startuml ManageSkill
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant SkillView [
  <<view>>
  :SkillPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Skill Page
activate SkillView
SkillView -->> Admin: Show Skill Page
deactivate DashboardView
deactivate SkillView
deactivate Admin
@enduml
