@startuml ManageInstructorRegistration
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Instructor Registration List Page;
|System|
:Show Instructor Registration List Page;
stop
@enduml
