@startuml ManageInstructorRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant InstructorRegistrationView [
  <<view>>
  :InstructorRegistrationPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Instructor Registration List Page
activate InstructorRegistrationView
DashboardView -> InstructorRegistrationView: Redirect to Instructor Registration List Page
deactivate DashboardView

InstructorRegistrationView -->> Admin: Show Instructor Registration List Page

deactivate Admin
deactivate InstructorRegistrationView
@enduml
