@startuml Edit Category
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Categories Page;
|System|
:Show Categories Page;
|Admin|
:Click Edit Button on Category;
|System|
:Show Edit Category Modal;
|Admin|
repeat :Edit Data in Form;
:Click Save Button;
|System|
:Validate Data;
backward: Show Error Message;
repeat while(valid?) is (no)
-> yes;
:Show Success Popup;
:Close Modal;
stop
@enduml
