@startuml EditCategory
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CategoriesView [
  <<view>>
  :CategoriesPage
]

participant EditCategoryModalView [
  <<view>>
  :EditCategoryModal
]

participant CategoryController [
  <<controller>>
  :CategoryController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Categories Page
activate CategoriesView
DashboardView -> CategoriesView: Redirect to Categories Page
deactivate DashboardView

CategoriesView -->> Admin: Show Categories Page

Admin -> CategoriesView: Click Edit Button on Category

activate EditCategoryModalView
CategoriesView -> EditCategoryModalView: Open Edit Category Form Modal
EditCategoryModalView -->> Admin: Show Edit Category Form Modal

Admin -> EditCategoryModalView: Edit Data in Form
Admin -> EditCategoryModalView: Click Save Button

activate CategoryController
EditCategoryModalView -> CategoryController: editCategory()
deactivate EditCategoryModalView
alt invalid
    CategoryController -->> CategoriesView: Return Error Message
    CategoriesView -->> Admin: showErrorPopup()
else valid
    CategoryController -->> CategoriesView: Return Success Message
    CategoriesView -->> Admin: showSuccessPopup()
end

deactivate CategoryController

deactivate Admin
deactivate CategoriesView
@enduml
