@startuml AddShift
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ShiftView [
  <<view>>
  :ShiftPage
]

participant AddShiftModalView [
  <<view>>
  :AddShiftModal
]

participant ShiftController [
  <<controller>>
  :ShiftController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Shift Page
activate ShiftView
DashboardView -> ShiftView: Redirect to Shift Page
deactivate DashboardView

ShiftView -->> Admin: Show Shift Page

Admin -> ShiftView: Click Add Button

activate AddShiftModalView
ShiftView -> AddShiftModalView: Open Shift Form Modal
AddShiftModalView -->> Admin: Show Shift Form Modal

Admin -> AddShiftModalView: Fill Shift Form
Admin -> AddShiftModalView: Click Save Button on Modal

activate ShiftController
AddShiftModalView -> ShiftController: addShift()
deactivate AddShiftModalView
alt invalid
    ShiftController -->> ShiftView: Return Error Message
    ShiftView -->> Admin: showErrorPopup()
else valid
    ShiftController -->> ShiftView: Return Success Message
    deactivate ShiftController

    ShiftView -->> Admin: showSuccessPopup()
end

deactivate Admin
deactivate ShiftView
@enduml
