@startuml EnrollNewCourse
actor Student
participant EnrollmentsPageView [
  <<view>>
  :EnrollmentsPage
]

participant ConfirmationModalView [
  <<view>>
  :ConfirmationModal
]

participant CourseEnrollmentController [
    <<controller>>
    :CourseEnrollmentController
]

activate Student
Student -> EnrollmentsPageView: Visit Enrollments Page
activate EnrollmentsPageView
EnrollmentsPageView -->> Student: Show Enrollments Page

Student -> EnrollmentsPageView: Click the Register button for a Course
activate ConfirmationModalView
EnrollmentsPageView -> ConfirmationModalView: Open Confirmation Modal for Enrollment
ConfirmationModalView -->> Student: Show Confirmation Modal

Student -> ConfirmationModalView: Confirm Enrollment
activate CourseEnrollmentController
ConfirmationModalView -> CourseEnrollmentController: enrollCourse()
CourseEnrollmentController -->> EnrollmentsPageView: Return Success Message
deactivate CourseEnrollmentController

EnrollmentsPageView -> ConfirmationModalView: closeModal()
deactivate ConfirmationModalView
EnrollmentsPageView -->> Student: showSuccessPopup()
deactivate Student
deactivate EnrollmentsPageView
@enduml
