@startuml DeleteChat
actor User
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ClassChatPageView [
    <<view>>
    :ClassChatPage
]

participant ConfirmationModalView [
    <<view>>
    :ConfirmationModal
]

participant ChatController [
  <<controller>>
  :ChatController
]

activate User
activate LoginPageView
User -> LoginPageView: Login as Student or Instructor
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard
deactivate LoginPageView

DashboardView -->> User: Show Dashboard

User -> DashboardView: Visit Class Chat Page
activate ClassChatPageView
DashboardView -> ClassChatPageView: Redirect to Class Chat Page
deactivate DashboardView

ClassChatPageView -->> User: Show Class Chat Page

User -> ClassChatPageView: Click Delete Button on a Chat
activate ConfirmationModalView
ClassChatPageView -> ConfirmationModalView: Open Confirmation Modal
ConfirmationModalView -->> User: Show Confirmation Modal
User -> ConfirmationModalView: Click Confirm Button
activate ChatController
ConfirmationModalView -> ChatController: deleteChat()
deactivate ConfirmationModalView

ChatController -->> ClassChatPageView: Return Success Message
deactivate ChatController
ClassChatPageView -->> User: Update Chat List

deactivate User
deactivate ClassChatPageView
@enduml
