@startuml ManageTrialClassRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant TrialClassRegistrationView [
  <<view>>
  :TrialClassRegistrationPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Trial Class Registration Page
activate TrialClassRegistrationView
DashboardView -> TrialClassRegistrationView: Redirect to Trial Class Registration Page
deactivate DashboardView

TrialClassRegistrationView -->> Admin: Show Trial Class Registration Page

deactivate Admin
deactivate TrialClassRegistrationView
@enduml
