@startuml EditChat
actor User
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ClassChatPageView [
    <<view>>
    :ClassChatPage
]

participant EditChatFormView [
    <<view>>
    :EditChatForm
]

participant ChatController [
  <<controller>>
  :ChatController
]

activate User
activate LoginPageView
User -> LoginPageView: Login as Student or Instructor
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard
deactivate LoginPageView

DashboardView -->> User: Show Dashboard

User -> DashboardView: Visit Class Chat Page
activate ClassChatPageView
DashboardView -> ClassChatPageView: Redirect to Class Chat Page
deactivate DashboardView

ClassChatPageView -->> User: Show Class Chat Page

User -> ClassChatPageView: Click Edit Button on a Chat
activate EditChatFormView
ClassChatPageView -> EditChatFormView: Toggle Edit Form for the selected Chat
deactivate ClassChatPageView

EditChatFormView -->> User: Show Edit Form for the selected Chat

User -> EditChatFormView: Edit the Chat in the Chatbox
User -> EditChatFormView: Click Save Button

activate ChatController
EditChatFormView -> ChatController: editChat()
alt invalid
    ChatController -->> EditChatFormView: Return Error Message
    EditChatFormView -->> User: showErrorPopup()
else valid
    ChatController -->> EditChatFormView: Return Success Message
    EditChatFormView -->> User: Update Chat List
end

deactivate User
deactivate EditChatFormView
deactivate ChatController
@enduml
