@startuml Delete Class
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Classes Page;
|System|
:Show Classes Page;
|Admin|
:Click Delete Button on a Class;
|System|
:Show Confirmation Modal;
|Admin|
:Click Confirm Button in Modal;
|System|
:Show Success Popup;
stop
@enduml
