@startuml Logout
actor User
participant HomePageView [
  <<view>>
  :HomePage
]

activate User
activate HomePageView
User -> HomePageView: Visit Home Page
HomePageView -->> User: Show Home Page
User -> HomePageView: Click Avatar on Navigation Bar
HomePageView -> HomePageView: Show Logout Dropdown Menu

User -> HomePageView: Click Logout Button in Dropdown Menu

participant AuthController [
  <<controller>>
  :AuthController
]

activate AuthController
HomePageView -> AuthController: logoutUser()
AuthController -->> HomePageView: Return Success Message
HomePageView -->> User: Show Success Popup
HomePageView -->> User: Redirect to Home Page

deactivate User
deactivate HomePageView
deactivate AuthController
@enduml
