@startuml AddFAQ
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant FAQView [
  <<view>>
  :FAQPage
]

participant AddFAQModalView [
  <<view>>
  :AddFAQModal
]

participant FAQController [
  <<controller>>
  :FAQController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit FAQ Page
activate FAQView
DashboardView -> FAQView: Redirect to FAQ Page
deactivate DashboardView

FAQView -->> Admin: Show FAQ Page

Admin -> FAQView: Click Add Button on FAQ Page

activate AddFAQModalView
FAQView -> AddFAQModalView: Open FAQ Form Modal
AddFAQModalView -->> Admin: Show FAQ Form Modal

Admin -> AddFAQModalView: Fill FAQ Form
Admin -> AddFAQModalView: Click Save Button on Modal

activate FAQController
AddFAQModalView -> FAQController: addFAQ()
deactivate AddFAQModalView
alt invalid
    FAQController -->> FAQView: Return Error Message
    FAQView -->> Admin: showErrorPopup()
else valid
    FAQController -->> FAQView: Return Success Message
    FAQView -->> Admin: showSuccessPopup()
end

deactivate FAQController

deactivate Admin
deactivate FAQView
@enduml
