@startuml EditProfile
actor User
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ProfilePageView [
  <<view>>
  :ProfilePage
]

participant EditProfilePageView [
  <<view>>
  :EditProfilePage
]

participant AccountController [
  <<controller>>
  :AccountController
]

activate User
activate LoginPageView
User -> LoginPageView: Login
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> User: Show Dashboard Page

User -> DashboardView: Visit Profile Page
activate ProfilePageView
DashboardView -> ProfilePageView: Redirect to Profile Page
deactivate DashboardView

ProfilePageView -->> User: Show Profile Page

User -> ProfilePageView: Click Edit Profile Button
activate EditProfilePageView
ProfilePageView -> EditProfilePageView: Redirect to Edit Profile Page
deactivate ProfilePageView

EditProfilePageView -->> User: Show Edit Profile Page

User -> EditProfilePageView: Fill Edit Profile Form
User -> EditProfilePageView: Click Save Button

activate AccountController
EditProfilePageView -> AccountController: editAccount()

alt invalid
  AccountController -->> EditProfilePageView: Return Error Message
  EditProfilePageView -->> User: showErrorPopup()
else valid
  AccountController -->> EditProfilePageView: Return Success Message
  EditProfilePageView -->> User: showSuccessPopup()
end

deactivate EditProfilePageView
deactivate User
deactivate EditProfilePageView
deactivate AccountController
@enduml
