@startuml DeleteCoupon
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CouponView [
  <<view>>
  :CouponPage
]

participant DeleteCouponConfirmationModalView [
  <<view>>
  :DeleteCouponConfirmationModal
]

participant CouponController [
  <<controller>>
  :CouponController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Coupon Page
activate CouponView
DashboardView -> CouponView: Redirect to Coupon Page
deactivate DashboardView

CouponView -->> Admin: Show Coupon Page

Admin -> CouponView: Click Delete Button on a Coupon

activate DeleteCouponConfirmationModalView
CouponView -> DeleteCouponConfirmationModalView: Show Confirmation Modal

Admin -> DeleteCouponConfirmationModalView: Confirm Deletion

activate CouponController
DeleteCouponConfirmationModalView -> CouponController: deleteCoupon()
CouponController -->> DeleteCouponConfirmationModalView: Return Success Message
DeleteCouponConfirmationModalView -->> Admin: Show Success Popup (Coupon Deleted)
deactivate CouponController

deactivate Admin
deactivate CouponView
deactivate DeleteCouponConfirmationModalView
@enduml
