@startuml ManageLogo
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant LogoView [
  <<view>>
  :LogoPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Logo Page
activate LogoView
DashboardView -> LogoView: Redirect to Logo Page
deactivate DashboardView

LogoView -->> Admin: Show Logo Page

deactivate Admin
deactivate LogoView
@enduml
