@startuml ApproveTrialClassRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant TrialClassRegistrationView [
  <<view>>
  :TrialClassRegistrationPage
]

participant ApprovalConfirmationModalView [
  <<view>>
  :ApprovalConfirmationModal
]

participant TrialClassController [
  <<controller>>
  :TrialClassController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Trial Class Registration List Page
activate TrialClassRegistrationView
DashboardView -> TrialClassRegistrationView: Redirect to Trial Class Registration List Page
deactivate DashboardView

TrialClassRegistrationView -->> Admin: Show Trial Class Registration List Page

Admin -> TrialClassRegistrationView: Click Approve Button on a Trial Class Registration
activate ApprovalConfirmationModalView
TrialClassRegistrationView -> ApprovalConfirmationModalView: Open Confirmation Modal
ApprovalConfirmationModalView -->> Admin: Show Confirmation Modal
Admin -> ApprovalConfirmationModalView: Confirm Approval
activate TrialClassController
ApprovalConfirmationModalView -> TrialClassController: approveRegistration()
deactivate ApprovalConfirmationModalView

TrialClassController -->> TrialClassRegistrationView: Return Success Message
deactivate TrialClassController
TrialClassRegistrationView -->> Admin: showSuccessPopup()

deactivate Admin
deactivate TrialClassRegistrationView
@enduml
