@startuml RejectTrialClassRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant TrialClassRegistrationView [
  <<view>>
  :TrialClassRegistrationPage
]

participant RejectionConfirmationModalView [
  <<view>>
  :RejectionConfirmationModal
]

participant TrialClassController [
  <<controller>>
  :TrialClassController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Trial Class Registration List Page
activate TrialClassRegistrationView
DashboardView -> TrialClassRegistrationView: Redirect to Trial Class Registration List Page
deactivate DashboardView

TrialClassRegistrationView -->> Admin: Show Trial Class Registration List Page

Admin -> TrialClassRegistrationView: Click Reject Button on a Trial Class Registration
activate RejectionConfirmationModalView
TrialClassRegistrationView -> RejectionConfirmationModalView: Open Rejection Confirmation Modal
RejectionConfirmationModalView -->> Admin: Show Rejection Confirmation Modal
Admin -> RejectionConfirmationModalView: Confirm Rejection
activate TrialClassController
RejectionConfirmationModalView -> TrialClassController: rejectRegistration()
deactivate RejectionConfirmationModalView

TrialClassController -->> TrialClassRegistrationView: Return Success Message
deactivate TrialClassController
TrialClassRegistrationView -->> Admin: showSuccessPopup()

deactivate Admin
deactivate TrialClassRegistrationView
@enduml
