@startuml PublishProgram
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Programs Page;
|System|
:Show Programs Page;
|Admin|
:Click Edit Button on Program;
|System|
:Redirect to Program Details Page;
|Admin|
:Click Publish Button on Program Details Page;
|System|
:Show Success Popup;
stop
@enduml
