@startuml RejectInstructorRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant InstructorRegistrationView [
  <<view>>
  :InstructorRegistrationPage
]

participant ConfirmationModalView [
  <<view>>
  :ConfirmationModal
]

participant InstructorRegistrationController [
  <<controller>>
  :InstructorRegistrationController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Instructor Registration Page
activate InstructorRegistrationView
DashboardView -> InstructorRegistrationView: Redirect to Instructor Registration Page
deactivate DashboardView

InstructorRegistrationView -->> Admin: Show Instructor Registration Page

Admin -> InstructorRegistrationView: Click Reject Button on a Registration
activate ConfirmationModalView
InstructorRegistrationView -> ConfirmationModalView: Open Confirmation Modal
ConfirmationModalView -->> Admin: Show Confirmation Modal
Admin -> ConfirmationModalView: Confirm Rejection
activate InstructorRegistrationController
ConfirmationModalView -> InstructorRegistrationController: rejectRegistration()
deactivate ConfirmationModalView

InstructorRegistrationController -->> InstructorRegistrationView: Return Success Message
deactivate InstructorRegistrationController
InstructorRegistrationView -->> Admin: showSuccessPopup()

deactivate Admin
deactivate InstructorRegistrationView
@enduml
