@startuml DeleteGrade
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant GradeView [
  <<view>>
  :GradePage
]

participant DeleteGradeConfirmationModalView [
  <<view>>
  :DeleteGradeConfirmationModal
]

participant GradeController [
  <<controller>>
  :GradeController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Grade Page
activate GradeView
DashboardView -> GradeView: Redirect to Grade Page
deactivate DashboardView

GradeView -->> Admin: Show Grade Page

Admin -> GradeView: Click Delete Button on a Grade

activate DeleteGradeConfirmationModalView
GradeView -> DeleteGradeConfirmationModalView: Open Confirmation Modal
DeleteGradeConfirmationModalView -->> Admin: Show Confirmation Modal

Admin -> DeleteGradeConfirmationModalView: Confirm Deletion

activate GradeController
DeleteGradeConfirmationModalView -> GradeController: deleteGrade()
deactivate DeleteGradeConfirmationModalView
GradeController -->> GradeView: Return Success Message
GradeView -->> Admin: showSuccessPopup()
deactivate GradeController

deactivate Admin
deactivate GradeView
@enduml
