@startuml AddSkill
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant SkillView [
  <<view>>
  :SkillPage
]

participant AddSkillModalView [
  <<view>>
  :AddSkillModal
]

participant SkillController [
  <<controller>>
  :SkillController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Skill Page
activate SkillView
SkillView -->> Admin: Show Skill Page
deactivate DashboardView

Admin -> SkillView: Click Add Button

activate AddSkillModalView
SkillView -> AddSkillModalView: Open Skill Form Modal
AddSkillModalView -->> Admin: Show Skill Form Modal

Admin -> AddSkillModalView: Fill Skill Form
Admin -> AddSkillModalView: Click Save Button

activate SkillController
AddSkillModalView -> SkillController: addSkill()
deactivate AddSkillModalView
alt invalid
    SkillController -->> SkillView: Return Validation Result
    SkillView -->> Admin: showErrorMessage()
else valid
    SkillController -->> SkillView: Return Validation Result
    SkillView -->> Admin: showSuccessPopup()
end

deactivate SkillController
deactivate Admin
deactivate SkillView
@enduml
