@startuml ManageCourse
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ProgramDetailsView [
  <<view>>
  :ProgramDetailsPage
]

participant CoursesController [
  <<controller>>
  :CoursesController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Program Details Page
activate ProgramDetailsView
DashboardView -> ProgramDetailsView: Redirect to Program Details Page
deactivate DashboardView

ProgramDetailsView -->> Admin: Show Program Details Page

Admin -> ProgramDetailsView: View All Courses in the Program

activate CoursesController
ProgramDetailsView -> CoursesController: viewAllCourses()
CoursesController -->> ProgramDetailsView: Return Course Data
ProgramDetailsView -->> Admin: Display All Courses in the Program
deactivate CoursesController

deactivate Admin
deactivate ProgramDetailsView
@enduml
