@startuml DeleteFAQ
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant FAQView [
  <<view>>
  :FAQPage
]

participant DeleteFAQConfirmationModalView [
  <<view>>
  :DeleteFAQConfirmationModal
]

participant FAQController [
  <<controller>>
  :FAQController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit FAQ Page
activate FAQView
DashboardView -> FAQView: Redirect to FAQ Page
deactivate DashboardView

FAQView -->> Admin: Show FAQ Page

Admin -> FAQView: Click Delete Button on FAQ

activate DeleteFAQConfirmationModalView
FAQView -> DeleteFAQConfirmationModalView: Show Confirmation Modal

Admin -> DeleteFAQConfirmationModalView: Click Confirm Button on Modal

activate FAQController
DeleteFAQConfirmationModalView -> FAQController: deleteFAQ()
FAQController -->> DeleteFAQConfirmationModalView: Return Success Message
DeleteFAQConfirmationModalView -->> Admin: Show Success Popup (FAQ Deleted)
deactivate FAQController

deactivate Admin
deactivate FAQView
deactivate DeleteFAQConfirmationModalView
@enduml
