@startuml AddGrade
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant GradeView [
  <<view>>
  :GradePage
]

participant AddGradeModalView [
  <<view>>
  :AddGradeModal
]

participant GradeController [
  <<controller>>
  :GradeController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Grade Page
activate GradeView
DashboardView -> GradeView: Redirect to Grade Page
deactivate DashboardView

GradeView -->> Admin: Show Grade Page

Admin -> GradeView: Click Add Button

activate AddGradeModalView
GradeView -> AddGradeModalView: Show Modal with Grade Form

Admin -> AddGradeModalView: Fill Grade Form
Admin -> AddGradeModalView: Click Save Button

activate GradeController
AddGradeModalView -> GradeController: addGrade()
alt invalid
    GradeController -->> AddGradeModalView: Return Validation Result
    AddGradeModalView -->> Admin: Show Error Message
else valid
    GradeController -->> AddGradeModalView: Return Validation Result
    AddGradeModalView -->> Admin: Close Modal
    AddGradeModalView -->> Admin: Show Success Popup (Grade Added)
end

deactivate GradeController

deactivate Admin
deactivate GradeView
deactivate AddGradeModalView
@enduml
