@startuml ChangeShiftStatus
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ShiftView [
  <<view>>
  :ShiftPage
]

participant ShiftController [
  <<controller>>
  :ShiftController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Shift Page
activate ShiftView
DashboardView -> ShiftView: Redirect to Shift Page
deactivate DashboardView

ShiftView -->> Admin: Show Shift Page

Admin -> ShiftView: Click Change Status Button on Shift

activate ShiftController
ShiftView -> ShiftController: changeShiftStatus()
ShiftController -->> ShiftView: Return Success Message
ShiftView -->> Admin: showSuccessPopup()

deactivate ShiftView
deactivate ShiftController
deactivate Admin
deactivate ShiftView
@enduml
