@startuml ManageAssessment
actor Instructor
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ClassDetailView [
  <<view>>
  :ClassDetailPage
]

participant AssessmentPageView [
  <<view>>
  :ClassAssessmentPage
]

activate Instructor
activate LoginPageView
Instructor -> LoginPageView: Login as Instructor
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Instructor: Show Dashboard Page

Instructor -> DashboardView: Visit Class Detail Page
activate ClassDetailView
DashboardView -> ClassDetailView: Redirect to Class Detail Page
deactivate DashboardView

ClassDetailView -->> Instructor: Show Class Detail Page

Instructor -> ClassDetailView: Click Assessment Tab
activate AssessmentPageView
ClassDetailView -> AssessmentPageView: Redirect to Class Assessment Page
deactivate ClassDetailView

AssessmentPageView -->> Instructor: Show Class Assessment Page

@enduml
