@startuml ApproveCourseRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CourseRegistrationView [
  <<view>>
  :CourseRegistrationPage
]

participant ConfirmationModalView [
  <<view>>
  :ConfirmationModal
]

participant CourseRegistrationController [
  <<controller>>
  :CourseRegistrationController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Course Registration Page
activate CourseRegistrationView
DashboardView -> CourseRegistrationView: Redirect to Course Registration Page
deactivate DashboardView

CourseRegistrationView -->> Admin: Show Course Registration Page

Admin -> CourseRegistrationView: Click Approve Button on a Registration
activate ConfirmationModalView
CourseRegistrationView -> ConfirmationModalView: Open Confirmation Modal
ConfirmationModalView -->> Admin: Show Confirmation Modal
Admin -> ConfirmationModalView: Click Confirm Button
activate CourseRegistrationController
ConfirmationModalView -> CourseRegistrationController: approveRegistration()
deactivate ConfirmationModalView

CourseRegistrationController -->> CourseRegistrationView: Return Success Message
deactivate CourseRegistrationController
CourseRegistrationView -->> Admin: showSuccessPopup()

deactivate Admin
deactivate CourseRegistrationView
@enduml
