@startuml ManageCourseRegistration
|Admin|
start
:Login as Admin;
|System|
:Redirect to Dashboard Page;
|Admin|
:Visit Course Registration List Page;
|System|
:Show Course Registration List Page;
stop
@enduml
