@startuml ManageCourseRegistration
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CourseRegistrationView [
  <<view>>
  :CourseRegistrationPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Course Registration List Page
activate CourseRegistrationView
DashboardView -> CourseRegistrationView: Redirect to Course Registration List Page
deactivate DashboardView

CourseRegistrationView -->> Admin: Show Course Registration List Page

deactivate Admin
deactivate CourseRegistrationView
@enduml
