@startuml AddSessionReport
actor Instructor
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ClassDetailsPageView [
  <<view>>
  :ClassDetailsPage
]

participant SessionDetailsPageView [
  <<view>>
  :SessionDetailsPage
]

participant SessionReportFormModalView [
  <<view>>
  :SessionReportFormModal
]

participant SessionReportController [
  <<controller>>
  :SessionReportController
]

activate Instructor
activate LoginPageView
Instructor -> LoginPageView: Login as Instructor
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard
deactivate LoginPageView

DashboardView -->> Instructor: Show Dashboard

Instructor -> DashboardView: Visit Class Details Page
activate ClassDetailsPageView
DashboardView -> ClassDetailsPageView: Redirect to Class Details Page
deactivate DashboardView

ClassDetailsPageView -->> Instructor: Show Class Details Page

Instructor -> ClassDetailsPageView: Click "Session" Tab
ClassDetailsPageView -->> Instructor: Show All Sessions for the Class

Instructor -> ClassDetailsPageView: Select a Session
activate SessionDetailsPageView
ClassDetailsPageView -> SessionDetailsPageView: Redirect to Session Details Page
deactivate ClassDetailsPageView

SessionDetailsPageView -->> Instructor: Show Session Details

Instructor -> SessionDetailsPageView: Click "Session Report" Section
activate SessionReportFormModalView
SessionDetailsPageView -> SessionReportFormModalView: Open Session Report Form Modal

SessionReportFormModalView -->> Instructor: Show Session Report Form Modal

Instructor -> SessionReportFormModalView: Fill Session Report Form
Instructor -> SessionReportFormModalView: Click Save Button
activate SessionReportController
SessionReportFormModalView -> SessionReportController: saveSessionReport()
SessionReportController -->> SessionDetailsPageView: Return Success Message
deactivate SessionReportController
deactivate SessionReportFormModalView
SessionDetailsPageView -->> Instructor: showSuccessPopup()

deactivate SessionDetailsPageView
deactivate Instructor
deactivate ClassDetailsPageView
deactivate SessionDetailsPageView
deactivate SessionReportFormModalView
@enduml
