@startuml Create Class
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CreateClassesView [
  <<view>>
  :CreateClassesPage
]

participant ClassFormModalView [
  <<view>>
  :ClassFormModal
]

participant ClassController [
  <<controller>>
  :ClassController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Create Classes Page
activate CreateClassesView
DashboardView -> CreateClassesView: Redirect to Create Classes Page
deactivate DashboardView

CreateClassesView -->> Admin: Show Create Classes Page
Admin -> CreateClassesView: Click Add Button

activate ClassFormModalView
CreateClassesView -> ClassFormModalView: Open Class Form Modal
ClassFormModalView -->> Admin: Show Class Form Modal

Admin -> ClassFormModalView: Fill Class Form
Admin -> ClassFormModalView: Click Save Button

activate ClassController
ClassFormModalView -> ClassController: saveClass()
alt invalid
    ClassController -->> ClassFormModalView: Return Error Message
    ClassFormModalView -->> Admin: showErrorPopup()
else valid
    ClassController -->> ClassFormModalView: Return Success Message
    deactivate ClassController

    Admin -> CreateClassesView: Click Save Button on the Page

    activate ClassController
    CreateClassesView -> ClassController: saveClasses()
    ClassController -->> CreateClassesView: Return Success Message
    deactivate ClassController
    CreateClassesView -->> Admin: showSuccessPopup()
    CreateClassesView -->> Admin: Redirect to Classes Page
end


deactivate Admin
deactivate CreateClassesView
deactivate ClassFormModalView
@enduml
