@startuml Edit Class
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant ClassesView [
  <<view>>
  :ClassesPage
]

participant EditClassModalView [
  <<view>>
  :EditClassModal
]

participant ClassController [
  <<controller>>
  :ClassController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Classes Page
activate ClassesView
DashboardView -> ClassesView: Redirect to Classes Page
deactivate DashboardView

ClassesView -->> Admin: Show Classes Page
Admin -> ClassesView: Click Edit Button on a Class

activate EditClassModalView
ClassesView -> EditClassModalView: Show Modal with Edit Form

Admin -> EditClassModalView: Edit Data in Form
Admin -> EditClassModalView: Click Save Button on Modal

activate ClassController
EditClassModalView -> ClassController: editClassData()
alt invalid
    ClassController -->> EditClassModalView: Return Validation Result
    EditClassModalView -->> Admin: Show Error Message
else valid
    ClassController -->> EditClassModalView: Return Validation Result
    EditClassModalView -->> Admin: Close Modal
end

deactivate ClassController

deactivate Admin
deactivate ClassesView
deactivate EditClassModalView
@enduml
