@startuml Manage FAQ
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant FAQView [
  <<view>>
  :FAQPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit FAQ Page
activate FAQView
DashboardView -> FAQView: Redirect to FAQ Page
deactivate DashboardView

FAQView -->> Admin: Show FAQ Page

deactivate Admin
deactivate FAQView
@enduml
