@startuml ManageCoupon
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant CouponView [
  <<view>>
  :CouponPage
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Coupon Page
activate CouponView
DashboardView -> CouponView: Redirect to Coupon Page
deactivate DashboardView

CouponView -->> Admin: Show Coupon Page

deactivate Admin
deactivate CouponView
@enduml
