@startuml Reject Enrollment
actor Admin
participant LoginPageView [
  <<view>>
  :LoginPage
]

participant DashboardView [
  <<view>>
  :Dashboard
]

participant EnrollmentsView [
  <<view>>
  :EnrollmentsPage
]

participant RejectionConfirmationModalView [
  <<view>>
  :RejectionConfirmationModal
]

participant EnrollmentController [
  <<controller>>
  :EnrollmentController
]

activate Admin
activate LoginPageView
Admin -> LoginPageView: Login as Admin
activate DashboardView
LoginPageView -> DashboardView: Redirect to Dashboard Page
deactivate LoginPageView

DashboardView -->> Admin: Show Dashboard Page

Admin -> DashboardView: Visit Enrollments Page
activate EnrollmentsView
DashboardView -> EnrollmentsView: Redirect to Enrollments Page
deactivate DashboardView

EnrollmentsView -->> Admin: Show Enrollments Page

Admin -> EnrollmentsView: Click Reject Button on an Enrollment

activate RejectionConfirmationModalView
EnrollmentsView -> RejectionConfirmationModalView: Show Confirmation Modal

Admin -> RejectionConfirmationModalView: Click Confirm Button in Modal

activate EnrollmentController
RejectionConfirmationModalView -> EnrollmentController: rejectEnrollment()
EnrollmentController -->> RejectionConfirmationModalView: Return Success Message
RejectionConfirmationModalView -->> Admin: Show Success Popup (Enrollment Rejected)
deactivate EnrollmentController

deactivate Admin
deactivate EnrollmentsView
deactivate RejectionConfirmationModalView
@enduml
